title = "Relais"
baseURL = "https://relaisculture.com"
languageCode = "fr"
description = "Relais"
copyright = "© 2020"

[markup.goldmark.renderer]
unsafe= true

[params]
contact = "contact@relaisculture.com"

[permalinks]
articles = "/:slug"
