title = "Relais"
baseURL = "https://relaisculture.com"
languageCode = "fr"
description = "Relais"
copyright = "© 2020"

[markup.goldmark.renderer]
unsafe= true

[params]
contact = "juliegeffrin+rc[at]gmail.com"

[permalinks]
articles = "/:slug"
